# Generated by Django 3.0.7 on 2020-07-25 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_auto_20200628_1114'),
        ('form', '0003_auto_20200628_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s4_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='df1s4_t', to='acc.AdTestType1'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s5_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='df1s5_t', to='acc.AdTestType1'),
        ),
        migrations.AlterField(
            model_name='defibrilator_1',
            name='s6_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='df1s6_t', to='acc.AdTestType1'),
        ),
        migrations.AlterField(
            model_name='ecg_1',
            name='cal_dev1',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, related_name='e1caldev1', to='acc.CalDevice'),
        ),
        migrations.AlterField(
            model_name='infusionpump_1',
            name='s8_e1_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='cal_dev1',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, related_name='me1caldev1', to='acc.CalDevice'),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='s1_e1_hr',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='s1_e2_hr',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='s1_e3_hr',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='s1_e4_hr',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='s1_e5_hr',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='s1_e6_hr',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='s1_e7_hr',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='s1_e8_hr',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='s8_e1_bdisp',
            field=models.FloatField(blank=True, default=0.05, null=True),
        ),
        migrations.AlterField(
            model_name='monitorecg_1',
            name='s8_e1_slope',
            field=models.FloatField(blank=True, default=0.2, null=True),
        ),
        migrations.AlterField(
            model_name='monitorspo2_1',
            name='s4_e1_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ms1s4e1comment', to='acc.Comment'),
        ),
    ]
