# Generated by Django 3.0.7 on 2020-07-26 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_auto_20200628_1114'),
        ('form', '0004_auto_20200725_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spo2_1',
            name='s4_e1_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='sp1s4e1comment', to='acc.Comment'),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s4_e2_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='sp1s4e2comment', to='acc.Comment'),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s4_e3_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='sp1s4e3comment', to='acc.Comment'),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s4_e4_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='sp1s4e4comment', to='acc.Comment'),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s5_e1_a',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s5_e1_v',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s6_e1_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='sp1s6e1comment', to='acc.Comment'),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s6_e1_er',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s6_e1_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s7_e1_aplc',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s7_e1_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='sp1s7e1comment', to='acc.Comment'),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s7_e1_noaplc',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s7_e2_aplc',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s7_e2_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='sp1s7e2comment', to='acc.Comment'),
        ),
        migrations.AlterField(
            model_name='spo2_1',
            name='s7_e2_noaplc',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
