# Generated by Django 3.0.7 on 2020-06-18 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdAccStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'سلسله مراتب حسابها',
            },
        ),
        migrations.CreateModel(
            name='AdAzStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'وضعیت های آزمایش',
            },
        ),
        migrations.CreateModel(
            name='AdExcelArg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arg', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'آرگومان اکسل',
            },
        ),
        migrations.CreateModel(
            name='AdReqStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'وضعیت های درخواست',
            },
        ),
        migrations.CreateModel(
            name='AdTestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'کلاس تست',
            },
        ),
        migrations.CreateModel(
            name='AdTestType0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'نوع آزمایش',
            },
        ),
        migrations.CreateModel(
            name='AdTestType1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'کلاس تست 2',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='نام شهر')),
                ('eng_name', models.TextField(verbose_name='نام انگلیسی شهر')),
            ],
            options={
                'verbose_name_plural': 'شهر ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50, verbose_name='شرح توضیح')),
            ],
            options={
                'verbose_name_plural': 'توضیحات',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='نام شرکت')),
                ('en_name', models.TextField(verbose_name='نام انگلیسی شرکت')),
            ],
            options={
                'verbose_name_plural': 'شرکت های سازنده',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='نام کشور')),
            ],
            options={
                'verbose_name_plural': 'کشور ها',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='نوع دستگاه')),
            ],
            options={
                'verbose_name_plural': 'نوع دستگاه ها',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='نام بیمارستان')),
                ('address', models.TextField(verbose_name='آدرس بیمارستان')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.City', verbose_name='شهر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='شناسه کاربری بیمارستان')),
            ],
            options={
                'verbose_name_plural': '2_بیمارستان ها',
            },
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='شماره گواهی')),
            ],
            options={
                'verbose_name_plural': 'شماره گواهی',
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'پارامتر ها',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='شماره رکورد')),
            ],
            options={
                'verbose_name_plural': 'شماره رکورد',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='نام بخش')),
                ('eng_name', models.TextField(verbose_name='نام انگلیسی بخش')),
            ],
            options={
                'verbose_name_plural': 'بخش های بیمارستان',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatar/', verbose_name='تصویر کاربر')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signature/', verbose_name='تصویر امضا')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acc.AdAccStatus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شناسه کاربر')),
            ],
            options={
                'verbose_name_plural': '1_مشخصات کاربران',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='نام استان')),
                ('eng_name', models.TextField(verbose_name='نام انگلیسی استان')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.Country', verbose_name='نام کشور')),
            ],
            options={
                'verbose_name_plural': 'استان ها',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ میلادی دستگاه')),
                ('number', models.IntegerField(verbose_name='شماره درخواست')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.Hospital', verbose_name='نام بیمارستان')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acc.AdReqStatus', verbose_name='وضعیت درخواست')),
            ],
            options={
                'verbose_name_plural': '5_لیست درخواست ها',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='اسم مدل دستگاه')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.Company', verbose_name='شرکت سازنده')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.DeviceType', verbose_name='نوع دستگاه')),
            ],
            options={
                'verbose_name_plural': 'لیست دستگاه',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.Country', verbose_name='کشور'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.State', verbose_name='نام استان'),
        ),
        migrations.CreateModel(
            name='CalDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='نام دستگاه کالیبره')),
                ('serial', models.CharField(max_length=30, verbose_name='سریال دستگاه کالیبره')),
                ('calibration_date', models.DateField(verbose_name='تاریخ شروع کالیبراسیون')),
                ('calibration_Expire_date', models.DateField(verbose_name='تاریخ اتمام کالیبراسیون')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.Company', verbose_name='شرکت سازنده')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.DeviceType', verbose_name='نوع دستگاه')),
            ],
            options={
                'verbose_name_plural': '4_دستگاه های کنترل کیفی',
            },
        ),
        migrations.CreateModel(
            name='AllDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.TextField(blank=True, null=True, verbose_name='شماره سریال دستگاه')),
                ('property_number', models.IntegerField(blank=True, null=True, verbose_name='شماره اموال دستگاه')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.Hospital', verbose_name='نام بیمارستان')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.Device', verbose_name='نام مدل دستگاه')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.Section', verbose_name='نام بخش')),
            ],
            options={
                'verbose_name_plural': '3_دستگاه های ثبت شده',
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام لوازم جانبی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acc.Company', verbose_name='شرکت سازنده')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acc.DeviceType', verbose_name='نوع لوازم جانبی')),
            ],
            options={
                'verbose_name_plural': 'لوازم جانبی',
            },
        ),
    ]
